application/controllers/Welcome.php
application/views/theme/template.php

Fix the homepage download link, and remove the robots meta tag.

---

application/views/download.php

Updated for RC2

---

application/views/download.php

Fix download links.

---

application/config/config.php
application/views/docs.php
application/views/download.php

Update for 3.0 release

---

application/config/config.php
application/controllers/Welcome.php
application/views/docs.php
application/views/download.php
user_guide/readme.rst
userguide2/readme.rst

Handle user guides better

---

application/views/docs.php
application/views/download.php

Updated legacy per 2.2.2 release

---

application/views/errors/cli/error_exception.php
application/views/errors/html/error_exception.php

Add missing views ... oops!

---

application/views/theme/jumbotitle.php

github widget - remove unnecessary html attributes

---

application/controllers/Welcome.php
application/libraries/Github_api.php
application/views/theme/_github_widget.php

Remove PHP from the jumbotitle view fragment.
Maintain generality of gothub api integration, so we can use other fields.

View fragment adjustment

---

application/views/about.php
application/views/contribute.php
application/views/help.php
application/views/irc.php
application/views/legal.php
application/views/welcome.php

I noticed there are some clean ups ongoing. Some files still have mixed indentations. I am trying to help the clean-ups by converting spaces to tabs. Are tabs preferred?

clean up: convert spaces to tabs

---

application/views/docs.php
application/views/download.php
application/views/welcome.php

Shorten the view/download button text so it doesn't get cut off at smaller browser/device resolutions.
Added back the news & threads headings I accidentally deleted earlier.

Improve readability

---

.htaccess

Address vulnerabilities reported by the security team

---

assets/css/style.css

Fix small device button(a element) text cut off problem.

---

application/views/docs.php

Release prep

---

application/core/MY_Controller.php

Recommendations from the security team.

Set headers for better security

---

application/controllers/Contribute.php
application/controllers/Download.php
application/core/MY_Controller.php
application/libraries/Github_api.php
application/views/contribute.php
application/views/theme/_heros.php

Beefed up the github api wrapper to download more repo info, specifically contributors,
so that we can acknoeledge them on the "contribute" page.
(Started out trying to show hashes for downloads, hence the name of the branch.)

Acknowledge contributors

---

application/config/config.php
application/controllers/Addons.php
application/views/addons.php
assets/css/style.css

@jim-parry: here is my UI mock addons page

Mock Addons UI

---

composer.json

A super minor fix.
Signed-off-by: Hongyi Zhang <hongyi73.zhang@gmail.com>

update composer.json as https is fully supported now

---

application/views/addons.php
assets/css/style.css

Here is a mock of the categories index view. Intentionally simple.
Feedback & changes?

Categories Grid

---

application/views/download.php

Fix button link colours for consistency

---

application/controllers/Welcome.php

Escape the subject field for posts from MyBB

---

application/config/config.php
application/controllers/Welcome.php
application/views/docs.php
application/views/download.php

Release 3.0.4

---

application/config/config.php
application/controllers/Welcome.php
application/views/docs.php
application/views/download.php

Release 3.0.5

---

application/config/config.php
application/controllers/Welcome.php
application/views/docs.php
application/views/download.php

Release 3.0.6

---

application/controllers/Contribute.php
application/views/contribute.php
application/views/responsible.php

Added a "responsible disclosure" page, off of "contribute".

Responsible disclosure

---

application/core/MY_Controller.php

Fix active menu item highlighting. Closes #94

---

application/config/config.php
application/controllers/Welcome.php
application/views/docs.php
application/views/download.php

Update for 3.1.1

---

application/config/config.php
application/controllers/Welcome.php
application/views/docs.php
application/views/download.php

Update for 3.1.2

---

application/views/community.php
application/views/contribute.php
application/views/help.php
application/views/legal.php
application/views/theme/_github_widget.php
application/views/theme/_heros.php

Detectify was complaining about a number of "target=_blank" attributes on links.
Have added the recommended "rel" attribute.

FIXDetectify issues

---

application/config/config.php
public/.htaccess
public/crossdomain.xml
public/opensearch.xml

- opensearch
- crossdomain policy (possibly preventing certain attacks)
- referrer policy header
- fix htaccess syntax error
- enable cookie secure (we are fully on TLS now) flag
- enable cookie httponly flag.

New features and some fixes

---

application/controllers/Welcome.php

Add Security section and remove some of the "benefits" which are excessive. Also, make the "benefits" looks more balance.

Refactor CI site homepage

---

application/config/config.php

Hide addins for now
